# This file is generated by Dist::Zilla::Plugin::CPANFile v6.037
# Do not edit this file directly. To change prereqs, edit the `dist.ini` file.

requires "Class::Load" => "0";
requires "Devel::StackTrace" => "0";
requires "Exception::Class" => "0";
requires "Exporter::Tiny" => "0";
requires "List::Util" => "v1.450.0";
# v5.18 adds deprecation warnings causing failing tests
requires "Module::Pluggable::Object" => "> 4.7";
requires "Moo" => "0";
requires "Ref::Util" => "0";
requires "Scalar::Util" => "0";
requires "constant" => "0";
requires "feature" => "0";
requires "namespace::clean" => "0";
requires "overload" => "0";
requires "parent" => "0";
requires "perl" => "5.010";
requires "strict" => "0";
requires "warnings" => "0";

on 'build' => sub {
  requires "Module::Build" => "0.28";
};

on 'test' => sub {
  if ($] < 5.012) {
	requires "Test::Fatal",   "==0.017";
    requires "Data::OptList", "==0.113";
  }

  requires "Exporter" => "0";
  requires "FindBin" => "0";
  requires "Hash::Util" => "0";
  requires "Path::Tiny" => "0";
  requires "Safe::Isa" => "0";
  requires "Sub::Install" => "0";
  requires "Sub::Name" => "0";
  requires "Sub::Override" => "0";
  requires "Sub::Uplevel" => "0";
  requires "Syntax::Construct" => "0";
  requires "Test::Deep"                   => ($] < 5.012) ? "==1.130" : ();
  requires "Test::Deep::Cmp" => "0";
  requires "Test::Exception" => "0";
  requires "Test::More" => "0.94";
  requires "Test::Warnings" => "0";
  requires "lib" => "0";
  requires "require::relative" => "0";
};

on 'configure' => sub {
  requires "Module::Build" => "0.28";
};

on 'develop' => sub {
  requires "Test::EOL" => "0";
  requires "Test::More" => "0.88";
};
